# render.yaml — master-bot-v.alpaca (Paper)

envVarGroups:
  # ===== Shared config & guards (applies to all workers) =====
  - name: bot-common
    envVars:
      - key: ALPACA_TRADE_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_DATA_BASE_URL
        value: https://data.alpaca.markets
      - key: ALPACA_PAPER
        value: "1"
      - key: ALPACA_TIME_IN_FORCE
        value: day
      - key: MARKET_TZ
        value: America/New_York
      - key: ALLOWED_EXCHANGES
        value: NASD,NASDAQ,NYSE,XNAS,XNYS
      - key: MIN_PRICE
        value: "3.0"

      # Global defaults for guards/sizing (tweak as you like)
      - key: START_EQUITY
        value: "100000"
      - key: DAILY_TP_PCT
        value: "10"
      - key: DAILY_DD_PCT
        value: "5"
      - key: MAX_CONCURRENT_POSITIONS
        value: "200"
      - key: CONF_THR
        value: "0.7"
      - key: R_MULT
        value: "3.0"
      - key: SCANNER_MIN_TODAY_VOL
        value: "20000"
      - key: TF_MIN_LIST
        value: "1,2,3,5,10"

  # ===== Alpaca accounts (you will set the secrets in the dashboard) =====
  - name: alpaca-acct-A   # Shared by Merged + Sentiment
    envVars:
      - key: ALPACA_KEY_ID
        value: ""         # <-- Fill in Render after creating the Blueprint
      - key: ALPACA_SECRET_KEY
        value: ""         # <-- Fill in Render after creating the Blueprint
  - name: alpaca-acct-B   # Ranked
    envVars:
      - key: ALPACA_KEY_ID
        value: ""
      - key: ALPACA_SECRET_KEY
        value: ""
  - name: alpaca-acct-C   # TradingBot
    envVars:
      - key: ALPACA_KEY_ID
        value: ""
      - key: ALPACA_SECRET_KEY
        value: ""

services:
  # ========== 1) ML_Merged ==========
  - type: worker
    name: ml-merged
    env: docker
    repo: https://github.com/your-org-or-user/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python ml_merged_app.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-A
      - key: STRATEGY_TAG
        value: ml_merged

  # ========== 2) ML_Sentiment (renamed file) ==========
  - type: worker
    name: ml-sentiment
    env: docker
    repo: https://github.com/your-org-or-user/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python ml_sentiment.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-A     # shares account A with Merged
      - key: STRATEGY_TAG
        value: ml_sentiment

  # ========== 3) Ranked ==========
  - type: worker
    name: ranked
    env: docker
    repo: https://github.com/your-org-or-user/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python Ranked_ML.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-B     # uses account B
      - key: STRATEGY_TAG
        value: ranked

  # ========== 4) TradingBot ==========
  - type: worker
    name: trading-bot
    env: docker
    repo: https://github.com/your-org-or-user/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python app.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-C     # uses account C
      - key: STRATEGY_TAG
        value: trading_bot
