# render.yaml — master-bot-v.alpaca (Paper)

envVarGroups:
  - name: bot-common
    envVars:
      - key: ALPACA_TRADE_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_DATA_BASE_URL
        value: https://data.alpaca.markets
      - key: ALPACA_PAPER
        value: "1"
      - key: ALPACA_TIME_IN_FORCE
        value: day
      - key: MARKET_TZ
        value: America/New_York
      - key: ALLOWED_EXCHANGES
        value: NASD,NASDAQ,NYSE,XNAS,XNYS
      - key: MIN_PRICE
        value: "3.0"
      # Global guard/sizing defaults (override per worker if needed)
      - key: START_EQUITY
        value: "100000"
      - key: DAILY_TP_PCT
        value: "10"
      - key: DAILY_DD_PCT
        value: "5"
      - key: MAX_CONCURRENT_POSITIONS
        value: "200"
      - key: CONF_THR
        value: "0.7"
      - key: R_MULT
        value: "3.0"
      - key: SCANNER_MIN_TODAY_VOL
        value: "20000"
      - key: TF_MIN_LIST
        value: "1,2,3,5,10"

  # Alpaca accounts (set secrets in Render after creating Blueprint)
  - name: alpaca-acct-A   # shared by Merged + Sentiment
    envVars:
      - key: ALPACA_KEY_ID
        value: ""
      - key: ALPACA_SECRET_KEY
        value: ""
  - name: alpaca-acct-B   # Ranked
    envVars:
      - key: ALPACA_KEY_ID
        value: ""
      - key: ALPACA_SECRET_KEY
        value: ""
  - name: alpaca-acct-C   # TradingBot
    envVars:
      - key: ALPACA_KEY_ID
        value: ""
      - key: ALPACA_SECRET_KEY
        value: ""

services:
  - type: worker
    name: ml-merged
    env: docker
    repo: https://github.com/bkmcm9205/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python ml_merged_app.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-A
      - key: STRATEGY_TAG
        value: ml_merged

  - type: worker
    name: ml-sentiment
    env: docker
    repo: https://github.com/bkmcm9205/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python ml_sentiment.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-A
      - key: STRATEGY_TAG
        value: ml_sentiment

  - type: worker
    name: ranked
    env: docker
    repo: https://github.com/bkmcm9205/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python Ranked_ML.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-B
      - key: STRATEGY_TAG
        value: ranked

  - type: worker
    name: trading-bot
    env: docker
    repo: https://github.com/your-org-or-user/master-bot-v.alpaca
    branch: main
    autoDeploy: true
    plan: Starter
    dockerfilePath: Dockerfile
    dockerCommand: python app.py
    envVars:
      - fromGroup: bot-common
      - fromGroup: alpaca-acct-C
      - key: STRATEGY_TAG
        value: trading_bot
